from typing import ClassVar
from django import forms
from django.forms import ModelForm, Textarea, fields, widgets
from .models import *

class Personal_Readme_form(forms.ModelForm):
    class Meta:
        model = Personal_readme
        fields = '__all__'
        labels = {
            'name':'Your Name',
            'about':'About Yourself',
            'work_status':'Your Current work status',
            'resume_link':'Your Resume',
            'work_status':'Your current status',
            'system':'I prefer working on',
            'project1_link': 'Your portfolio link',
            'project2':'I am currently working on',
            'project3':'I am looking to collaborate on',
            'project4':'I am looking for help with',
            'project5':'Any other project',
            'programming_language':'Programming Languages',
            'frontend_language':'Frontend Languages',
            'backend_language':'Backend Languages',
            'mobile_app_devlopment':'Mobile App Devlopment',
            'aI_ML':'AI/ML',
            'database':'Database',
            'data_visualization':'Data Visualization',
            'devops':'Devops',
            'bASS':'Backend as a service (BaaS)',
            'framework':'Framework',
            'testing':'Testing',
            'software':'Software',
            'static_site_gen':'Static Site Genrators',
            'game_engine':'Game Engine',
            'automation':'Automation',
            'blockchain':'Blockchain',
            'others':"Others",
            'github':'Github',
            'twitter':'Twitter',
            'codepen':"Codepen",
            'dev':'Dev',
            'linkedin':'Linkedin',
            'kaggle':'Kaggle',
            'facebook':'Facebook',
            'instagram':'Instagram',
            'dribble':'Dribble',
            'behance':'Behance',
            'hashnode':'Hashnode',
            'medium':'Medium',
            'youtube':'Youtube',
            'hackerank':'Hackerrank',
            'leetcode':'Leetcode',
            'topcoder':'Topcoder',
            'hackerearth':'Hackerearth',
            'discord':'Discord',
            'rss':'RSS',
            'add_ons':'Add Ons',
            'buy_me_coffee':'Buy me coffee',
            'patreon':'Patreon',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': '  type your name','id':'name','font-size':'50px'}),
            'about_me': forms.TextInput(attrs={'placeholder': '  a short summary about yourself','id':'about_me'}),
            'resume_link': forms.TextInput(attrs={'placeholder':' link of your resume','id':'resume_link'}),
            'email_id': forms.EmailInput(attrs={'placeholder':'  your email id','id':'email_id'}),
            'project1_link': forms.TextInput(attrs={'placeholder':'  link of your portfolio/website','id':'project1_link'}),
            'project2': forms.TextInput(attrs={'placeholder':'  project name','id':'project2'}),
            'project2_link': forms.TextInput(attrs={'placeholder':'  link of your project/github repo','id':'project2_link'}),
            'project3': forms.TextInput(attrs={'placeholder':'  project name','id':'project3'}),
            'project3_link': forms.TextInput(attrs={'placeholder':'  link of your project/github repo','id':'project3_link'}),
            'project4': forms.TextInput(attrs={'placeholder':'  project name','id':'project4'}),
            'project4_link': forms.TextInput(attrs={'placeholder':'  link of your project/github repo','id':'project4_link'}),
            'project5': forms.TextInput(attrs={'placeholder':'  project name','id':'project5'}),
            'project5_link': forms.TextInput(attrs={'placeholder':'  link of your project/github repo','id':'project5_link'}),
            'work_status' : forms.TextInput(attrs={'placeholder':'  your current status','id':'work_status'}),
            'work_status_link' : forms.TextInput(attrs={'placeholder':'  link of current working oraganization if any','id':'work_status_link'}),
            'system' : forms.CheckboxSelectMultiple(attrs={'id':'system'}),
            'programming_language' : forms.CheckboxSelectMultiple(attrs={'id':'programming_language'}),
            'frontend_language' : forms.CheckboxSelectMultiple(attrs={'id':'frontend_language'}),
            'backend_language' : forms.CheckboxSelectMultiple(attrs={'id':'backend_language'}),
            'mobile_app_devlopment' : forms.CheckboxSelectMultiple(attrs={'id':'mobile_app_devlopment'}),
            'aI_ML' : forms.CheckboxSelectMultiple(attrs={'id':'aI_ML'}),
            'database' : forms.CheckboxSelectMultiple(attrs={'id':'database'}),
            'data_visualization' : forms.CheckboxSelectMultiple(attrs={'id':'data_visualization'}),
            'devops' : forms.CheckboxSelectMultiple(attrs={'id':'devops'}),
            'bASS' : forms.CheckboxSelectMultiple(attrs={'id':'bASS'}),
            'framework' : forms.CheckboxSelectMultiple(attrs={'id':'framework'}),
            'testing' : forms.CheckboxSelectMultiple(attrs={'id':'testing'}),
            'software' : forms.CheckboxSelectMultiple(attrs={'id':'software'}),
            'static_site_gen' : forms.CheckboxSelectMultiple(attrs={'id':'static_site_gen'}),
            'game_engine' : forms.CheckboxSelectMultiple(attrs={'id':'game_engine'}),
            'automation' : forms.CheckboxSelectMultiple(attrs={'id':'automation'}),
            'blockchain' : forms.CheckboxSelectMultiple(attrs={'id':'blockchain'}),
            'others' : forms.CheckboxSelectMultiple(attrs={'id':'others'}),  
            'github': forms.TextInput(attrs={'placeholder':'  link of your github profile','id':'github'}),
            'twitter': forms.TextInput(attrs={'placeholder':'  link of your twitter profile','id':'twitter'}),
            'codepen': forms.TextInput(attrs={'placeholder':'  link of your codepen profile','id':'codepen'}),
            'dev': forms.TextInput(attrs={'placeholder':'  link of your dev profile','id':'dev'}),
            'linkedin': forms.TextInput(attrs={'placeholder':'  link of your linkedin profile','id':'linkedin'}),
            'kaggle': forms.TextInput(attrs={'placeholder':'  link of your kaggle profile','id':'kaggle'}),
            'facebook': forms.TextInput(attrs={'placeholder':'  link of your facebook profile','id':'facebook'}),
            'instagram': forms.TextInput(attrs={'placeholder':'  link of your instagram profile','id':'instagram'}),
            'dribble': forms.TextInput(attrs={'placeholder':'  link of your dribble profile','id':'dribble'}),
            'behance': forms.TextInput(attrs={'placeholder':'  link of your behance profile','id':'behance'}),
            'hashnode': forms.TextInput(attrs={'placeholder':'  link of your hashnode profile','id':'hashnode'}),
            'medium': forms.TextInput(attrs={'placeholder':'  link of your medium page','id':'medium'}),
            'youtube': forms.TextInput(attrs={'placeholder':'  link of your youtube channel','id':'youtube'}),
            'hackerank': forms.TextInput(attrs={'placeholder':'  link of your hackerrank profile','id':'hackerank'}),
            'leetcode': forms.TextInput(attrs={'placeholder':'  link of your leetcode profile','id':'leetcode'}),
            'topcoder': forms.TextInput(attrs={'placeholder':'  link of your topcoder profile','id':'topcoder'}),
            'hackerearth': forms.TextInput(attrs={'placeholder':'  link of your hackerearth profile','id':'hackerearth'}),
            'discord': forms.TextInput(attrs={'placeholder':'  link of your discord profile','id':'discord'}),
            'rss': forms.TextInput(attrs={'placeholder':'  link of your rss profile','id':'rss'}),
            'add_ons':forms.CheckboxSelectMultiple(attrs={'id':'add_ons'}),
            'buy_me_coffee': forms.TextInput(attrs={'placeholder':'  link of your buy me coffee page','id':'buy_me_coffee'}),
            'patreon': forms.TextInput(attrs={'placeholder':'   link of your patreon page','id':'patreon'}),
        }